Fix #5876: Windows build fails with OpenCV 3.4.10
Update the required OpenCV version to 3.4.12.
The project uses `CAP_PROP_ORIENTATION_AUTO` contant that was introduced in OpenCV 3.4.12,
thus is not accesible in OpenCV 3.4.10
https://github.com/opencv/opencv/commit/f0271e54d90b3af62301f531f5f00995b00d7cd6

Using of OpenCV 3.4.10 leads to a build error
```
mediapipe/calculators/video/opencv_video_decoder_calculator.cc(116): error C2039: 'CAP_PROP_ORIENTATION_AUTO': is not a member of 'cv'
external/windows_opencv/include\opencv2/videoio.hpp(71): note: see declaration of 'cv'
mediapipe/calculators/video/opencv_video_decoder_calculator.cc(116): error C2065: 'CAP_PROP_ORIENTATION_AUTO': undeclared identifier
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
```